void message_init(void);
void message_deinit(void);
void getSavedStops(void);
void getNearestStops(void);
void getNearestBus(void);
void getNearestTrain(void);
void getNearestTram(void);
void getStop(char *id);
void saveStop(char *id);
void removeStop(char *id);